program: src/wandb_main.py
name: 6D different batch sizes
method: grid
metric:
  goal: minimize
  name: train_intermodality_loss
parameters:
  temperature:
    values: [0.01]
  learnable_temperature:
    values: [False]
  clip_projection_dim: 
    values: [6] # 512
  batch_size: 
    values: [64, 128, 256]
  vision_model: 
    values: [VIT] # RN50 or VIT or VIT16
  use_scheduler: 
    values: [no] # COSINE or EXP
  schedule_every:
    values: [400] # num steps NOT epochs
  n_warmup_steps:
    values: [10000]
  weight_decay:
    values: [0.1]
  train_from_scratch:
    values: [True]
  continue_from_checkpoint: 
    values: [False]
  train_from_pretrained: 
    values: [False]
  finetune_clip_backbone: 
    values: [False]
  finetune_multi_layer_projection: 
    values: [False]



  # LOSS STUFF
  intra_modality_loss: 
    values: [False]
  uniformity_loss: 
    values: [False]
  alignment_loss: 
    values: [False]
  cross_uniformity_loss: 
    values: [False]
  remove_contrastive_loss: 
    values: [False]
  cyclip_loss: 
    values: [False]
  simclr_loss: 
    values: [False]
  # weight_decay: min: 0.2 max: 0.6



  lr: 
    values: [1e-6] # 5e-4 from CyClip paper
  n_epochs: 
    values: [25]
  num_workers: 
    values: [8]
  zero_shot_acc_num_workers: 
    values: [4]

  # DATASET STUFF
  # dataset: values: [ClipDatasets.CONCEPTUAL_CAPTIONS.value]
  dataset: 
    values: [ClipDatasets.MSCOCO.value]
  validation_dataset_size: 
    values: [512]
  validation_batch_size: 
    values: [512]
  use_small_trainloader: 
    values: [False] 
  cifar10_acc: 
    values: [False] 
  use_train_as_val: 
    values: [False] # SET

  save_encoder_hidden_states: 
    values: [False]
  n_embeds_to_save: 
    values: [512]

  seed: 
    values: [44]